# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
  pipelines:
  - pipeline: tech-arti-blogs.pipelines-javascript-docker    # Name of the pipeline resource
    source: tech-arti-blogs.pipelines-dotnet-core # Name of the pipeline referenced by the pipeline resource
    project: Configuring Pipeline # Required only if the source pipeline is in another project
    trigger: true # enable the trigger 

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
        tags: |
          $(tag)
